version: "3.7"
# Used for remote development with VSCode.
services:

  # ------------------------------------
  # clasp
  #
  clasp:
    image: dev-clasp
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./project/:/home/project/
      - node_modules:/home/project/node_modules/
    working_dir: /home/project

volumes:
  node_modules:
    driver: local
